CREATE TABLE popular_location_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calculated_at timestamp(6) with time zone NOT NULL,
    window_started_at timestamp(6) with time zone NOT NULL,
    window_ended_at timestamp(6) with time zone NOT NULL,
    ranking_limit integer NOT NULL,
    algorithm_version character varying(40) NOT NULL,
    CONSTRAINT chk_popular_location_snapshot_window
        CHECK (window_started_at < window_ended_at),
    CONSTRAINT chk_popular_location_snapshot_limit
        CHECK (ranking_limit BETWEEN 1 AND 20)
);

CREATE INDEX idx_popular_location_snapshot_calculated
    ON popular_location_snapshot (calculated_at);

CREATE TABLE popular_location_rank (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id bigint NOT NULL,
    location_id bigint NOT NULL,
    ranking_position integer NOT NULL,
    previous_ranking_position integer,
    rank_change integer,
    movement character varying(10) NOT NULL,
    unique_reporter_count bigint NOT NULL,
    report_count bigint NOT NULL,
    latest_report_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_popular_location_rank_snapshot
        FOREIGN KEY (snapshot_id)
        REFERENCES popular_location_snapshot (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_popular_location_rank_location
        FOREIGN KEY (location_id)
        REFERENCES location (id),
    CONSTRAINT uk_popular_location_rank_snapshot_position
        UNIQUE (snapshot_id, ranking_position),
    CONSTRAINT uk_popular_location_rank_snapshot_location
        UNIQUE (snapshot_id, location_id),
    CONSTRAINT chk_popular_location_rank_position
        CHECK (ranking_position BETWEEN 1 AND 20),
    CONSTRAINT chk_popular_location_previous_rank
        CHECK (previous_ranking_position IS NULL
            OR previous_ranking_position BETWEEN 1 AND 20),
    CONSTRAINT chk_popular_location_rank_movement
        CHECK (movement IN ('NEW', 'UP', 'DOWN', 'SAME')),
    CONSTRAINT chk_popular_location_rank_counts
        CHECK (unique_reporter_count >= 0 AND report_count >= 1)
);

CREATE INDEX idx_popular_location_rank_snapshot
    ON popular_location_rank (snapshot_id, ranking_position);

CREATE INDEX idx_weather_report_popular_window
    ON weather_report (created_at DESC, location_id)
    INCLUDE (id, author_member_id, author_anonymous_key);
