CREATE TABLE report_consent (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    report_id bigint NOT NULL,
    terms_type character varying(20) NOT NULL,
    version character varying(20) NOT NULL,
    agreed_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_report_consent_report
        FOREIGN KEY (report_id)
        REFERENCES weather_report (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_report_consent_report_type
        UNIQUE (report_id, terms_type),
    CONSTRAINT chk_report_consent_terms_type
        CHECK (terms_type IN ('SERVICE', 'PRIVACY'))
);

CREATE INDEX idx_report_consent_report
    ON report_consent (report_id);
