ALTER TABLE member
    ADD COLUMN role character varying(20) NOT NULL DEFAULT 'MEMBER';

ALTER TABLE member
    ADD CONSTRAINT chk_member_role
        CHECK (role IN ('MEMBER', 'MODERATOR', 'ADMIN'));

CREATE TABLE member_role_change (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    target_member_id bigint NOT NULL,
    changed_by_member_id bigint NOT NULL,
    previous_role character varying(20) NOT NULL,
    new_role character varying(20) NOT NULL,
    CONSTRAINT chk_member_role_change_previous
        CHECK (previous_role IN ('MEMBER', 'MODERATOR', 'ADMIN')),
    CONSTRAINT chk_member_role_change_new
        CHECK (new_role IN ('MEMBER', 'MODERATOR', 'ADMIN'))
);

CREATE INDEX idx_member_role_change_target
    ON member_role_change (target_member_id, created_at);
CREATE INDEX idx_member_role_change_admin
    ON member_role_change (changed_by_member_id, created_at);

ALTER TABLE weather_report
    ADD COLUMN moderation_status character varying(20) NOT NULL DEFAULT 'VISIBLE';

ALTER TABLE weather_report
    ADD CONSTRAINT chk_weather_report_moderation_status
        CHECK (moderation_status IN ('VISIBLE', 'HIDDEN', 'REMOVED'));

CREATE INDEX idx_weather_report_visible_location_created
    ON weather_report (location_id, created_at DESC, id DESC)
    WHERE moderation_status = 'VISIBLE';

CREATE TABLE report_flag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    report_id bigint NOT NULL,
    reporter_type character varying(20) NOT NULL,
    reporter_key character varying(64) NOT NULL,
    reason character varying(30) NOT NULL,
    detail character varying(500),
    status character varying(20) NOT NULL,
    processed_at timestamp(6) with time zone,
    processed_by_member_id bigint,
    resolution_note character varying(500),
    CONSTRAINT fk_report_flag_report
        FOREIGN KEY (report_id) REFERENCES weather_report (id) ON DELETE CASCADE,
    CONSTRAINT uk_report_flag_report_reporter
        UNIQUE (report_id, reporter_type, reporter_key),
    CONSTRAINT chk_report_flag_reporter_type
        CHECK (reporter_type IN ('MEMBER', 'ANONYMOUS')),
    CONSTRAINT chk_report_flag_reason
        CHECK (reason IN ('SPAM', 'ABUSE', 'HATE', 'SEXUAL', 'PRIVACY', 'FALSE_INFORMATION', 'OTHER')),
    CONSTRAINT chk_report_flag_status
        CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED'))
);

CREATE INDEX idx_report_flag_status_created
    ON report_flag (status, created_at);
CREATE INDEX idx_report_flag_report
    ON report_flag (report_id);

CREATE TABLE actor_block (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    blocker_type character varying(20) NOT NULL,
    blocker_key character varying(64) NOT NULL,
    blocked_type character varying(20) NOT NULL,
    blocked_key character varying(64) NOT NULL,
    CONSTRAINT uk_actor_block_pair
        UNIQUE (blocker_type, blocker_key, blocked_type, blocked_key),
    CONSTRAINT chk_actor_block_blocker_type
        CHECK (blocker_type = 'MEMBER'),
    CONSTRAINT chk_actor_block_blocked_type
        CHECK (blocked_type = 'MEMBER')
);

CREATE INDEX idx_actor_block_blocker
    ON actor_block (blocker_type, blocker_key);

CREATE TABLE actor_restriction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    actor_type character varying(20) NOT NULL,
    actor_key character varying(64) NOT NULL,
    source_report_id bigint,
    reason character varying(500) NOT NULL,
    expires_at timestamp(6) with time zone,
    created_by_member_id bigint NOT NULL,
    lifted_at timestamp(6) with time zone,
    lifted_by_member_id bigint,
    CONSTRAINT fk_actor_restriction_source_report
        FOREIGN KEY (source_report_id) REFERENCES weather_report (id) ON DELETE SET NULL,
    CONSTRAINT chk_actor_restriction_actor_type
        CHECK (actor_type IN ('MEMBER', 'ANONYMOUS'))
);

CREATE INDEX idx_actor_restriction_actor
    ON actor_restriction (actor_type, actor_key, lifted_at, expires_at);

CREATE TABLE moderation_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    action_type character varying(40) NOT NULL,
    admin_member_id bigint NOT NULL,
    report_id bigint,
    target_actor_type character varying(20),
    target_actor_key character varying(64),
    reason character varying(500) NOT NULL,
    CONSTRAINT fk_moderation_action_report
        FOREIGN KEY (report_id) REFERENCES weather_report (id) ON DELETE SET NULL,
    CONSTRAINT chk_moderation_action_type
        CHECK (action_type IN (
            'REPORT_HIDDEN', 'REPORT_RESTORED', 'REPORT_REMOVED',
            'FLAG_RESOLVED', 'FLAG_REJECTED',
            'AUTHOR_RESTRICTED', 'AUTHOR_RESTRICTION_LIFTED'
        )),
    CONSTRAINT chk_moderation_action_target_type
        CHECK (target_actor_type IS NULL OR target_actor_type IN ('MEMBER', 'ANONYMOUS'))
);

CREATE INDEX idx_moderation_action_report
    ON moderation_action (report_id, created_at);
CREATE INDEX idx_moderation_action_admin
    ON moderation_action (admin_member_id, created_at);
