-- 초기 스키마 (dev/prod Flyway baseline). local 은 ddl-auto 로 관리하며 이 파일을 쓰지 않는다.
-- 생성: local Postgres(Hibernate ddl-auto 결과)를 pg_dump --schema-only 로 추출해 정리.
-- 이후 스키마 변경은 V2__*.sql, V3__*.sql ... 로 추가한다.

CREATE TABLE feedback (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    author_member_id bigint,
    content character varying(500) NOT NULL
);
ALTER TABLE feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE location (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    admin_code character varying(20) NOT NULL,
    dong character varying(30) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    sido character varying(20) NOT NULL,
    sigungu character varying(30) NOT NULL
);
CREATE TABLE location_favorite (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    location_id bigint NOT NULL,
    member_id bigint NOT NULL
);
ALTER TABLE location_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME location_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE member (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    avatar_type character varying(20) NOT NULL,
    avatar_value character varying(100),
    email character varying(255),
    name character varying(30),
    nickname character varying(10),
    status character varying(20) NOT NULL,
    withdrawn_at timestamp(6) with time zone,
    CONSTRAINT member_avatar_type_check CHECK (((avatar_type)::text = ANY ((ARRAY['DEFAULT'::character varying, 'PRESET'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT member_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[])))
);
CREATE TABLE member_consent (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    agreed boolean NOT NULL,
    agreed_at timestamp(6) with time zone NOT NULL,
    member_id bigint NOT NULL,
    terms_type character varying(20) NOT NULL,
    version character varying(20) NOT NULL,
    CONSTRAINT member_consent_terms_type_check CHECK (((terms_type)::text = ANY ((ARRAY['SERVICE'::character varying, 'PRIVACY'::character varying, 'LOCATION'::character varying, 'MARKETING'::character varying])::text[])))
);
ALTER TABLE member_consent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME member_consent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE social_account (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone NOT NULL,
    provider character varying(20) NOT NULL,
    provider_email character varying(255),
    provider_user_id character varying(100) NOT NULL,
    member_id bigint NOT NULL,
    CONSTRAINT social_account_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[])))
);
ALTER TABLE social_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME social_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE thanks (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    actor_key character varying(64) NOT NULL,
    actor_type character varying(20) NOT NULL,
    report_id bigint NOT NULL,
    CONSTRAINT thanks_actor_type_check CHECK (((actor_type)::text = ANY ((ARRAY['MEMBER'::character varying, 'ANONYMOUS'::character varying])::text[])))
);
ALTER TABLE thanks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME thanks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE weather_report (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    author_anonymous_key character varying(36),
    author_member_id bigint,
    author_type character varying(20) NOT NULL,
    comment character varying(200),
    location_id bigint NOT NULL,
    precipitation character varying(20) NOT NULL,
    sunlight character varying(20) NOT NULL,
    temperature character varying(20) NOT NULL,
    CONSTRAINT weather_report_author_type_check CHECK (((author_type)::text = ANY ((ARRAY['MEMBER'::character varying, 'ANONYMOUS'::character varying])::text[]))),
    CONSTRAINT weather_report_precipitation_check CHECK (((precipitation)::text = ANY ((ARRAY['NONE'::character varying, 'LIGHT'::character varying, 'HEAVY'::character varying])::text[]))),
    CONSTRAINT weather_report_sunlight_check CHECK (((sunlight)::text = ANY ((ARRAY['LOW'::character varying, 'MODERATE'::character varying, 'STRONG'::character varying])::text[]))),
    CONSTRAINT weather_report_temperature_check CHECK (((temperature)::text = ANY ((ARRAY['COLD'::character varying, 'FRESH'::character varying, 'HOT'::character varying])::text[])))
);
ALTER TABLE weather_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE weather_report_image (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    display_order integer NOT NULL,
    storage_key character varying(255) NOT NULL,
    report_id bigint NOT NULL
);
ALTER TABLE weather_report_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather_report_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);
ALTER TABLE ONLY location_favorite
    ADD CONSTRAINT location_favorite_pkey PRIMARY KEY (id);
ALTER TABLE ONLY location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);
ALTER TABLE ONLY member_consent
    ADD CONSTRAINT member_consent_pkey PRIMARY KEY (id);
ALTER TABLE ONLY member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);
ALTER TABLE ONLY social_account
    ADD CONSTRAINT social_account_pkey PRIMARY KEY (id);
ALTER TABLE ONLY thanks
    ADD CONSTRAINT thanks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY location
    ADD CONSTRAINT uk_location_admin_code UNIQUE (admin_code);
ALTER TABLE ONLY location_favorite
    ADD CONSTRAINT uk_location_favorite_member_location UNIQUE (member_id, location_id);
ALTER TABLE ONLY member_consent
    ADD CONSTRAINT uk_member_consent_member_type UNIQUE (member_id, terms_type);
ALTER TABLE ONLY member
    ADD CONSTRAINT uk_member_nickname UNIQUE (nickname);
ALTER TABLE ONLY social_account
    ADD CONSTRAINT uk_social_account_provider_user UNIQUE (provider, provider_user_id);
ALTER TABLE ONLY thanks
    ADD CONSTRAINT uk_thanks_report_actor UNIQUE (report_id, actor_type, actor_key);
ALTER TABLE ONLY weather_report_image
    ADD CONSTRAINT weather_report_image_pkey PRIMARY KEY (id);
ALTER TABLE ONLY weather_report
    ADD CONSTRAINT weather_report_pkey PRIMARY KEY (id);
CREATE INDEX idx_location_dong ON location USING btree (dong);
CREATE INDEX idx_location_favorite_member ON location_favorite USING btree (member_id);
CREATE INDEX idx_member_consent_member ON member_consent USING btree (member_id);
CREATE INDEX idx_thanks_report ON thanks USING btree (report_id);
CREATE INDEX idx_weather_report_location_created ON weather_report USING btree (location_id, created_at);
