CREATE TABLE mobile_guest_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    anonymous_key character varying(36) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone
);

ALTER TABLE mobile_guest_credential
    ADD CONSTRAINT uk_mobile_guest_token_hash UNIQUE (token_hash);

ALTER TABLE mobile_guest_credential
    ADD CONSTRAINT uk_mobile_guest_anonymous_key UNIQUE (anonymous_key);

CREATE INDEX idx_mobile_guest_expires_at
    ON mobile_guest_credential (expires_at);
