plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation project(':auth')
    implementation project(':member')
    implementation project(':location')
    implementation project(':report')

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'net.logstash.logback:logstash-logback-encoder:8.1'
}
